server:
  port: 8080
  servlet:
    context-path: /dayday
spring:
  thymeleaf:
    mode: LEGACYHTML5
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/aaa?userSSL=true&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

